#!/bin/bash

# https://stackoverflow.com/a/57791854
# Works, provided you used command from README.md
#   that sets git hook directory.

clang-format --style=LLVM -i $(git diff --cached --name-only)


